#!/bin/bash -e

#Split the given dataset into a training set and a testing set with the given ratio to a given target directory
rm -r ${4}
mkdir ${4}
sed -n 1p $1 > header
sed '1d' $1 | gshuf > tmp
LINENUMBER="$(cat tmp | wc -l)"
sed -n "1,$((${LINENUMBER} * ${2} / ${3}))p" tmp > training.csv
sed -n "$((${LINENUMBER} * ${2} / ${3})),${LINENUMBER}p" tmp > testing.csv
rm tmp
cat header training.csv > training_.csv
cat header testing.csv > testing_.csv
mv training_.csv training.csv
mv testing_.csv testing.csv
rm header
mv training.csv ${4}
mv testing.csv ${4}
